apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-deployment
  labels:
    app: readiness

spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness

  template:
    metadata:
      labels:
        app: readiness

    spec:
      containers:
        - name: readiness
          image: registry.k8s.io/busybox
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
          readinessProbe:
           exec:
              command:
              - cat
              - /tmp/healthy
           initialDelaySeconds: 5
           periodSeconds: 5
